'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.261
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Этот класс создан автоматически классом StronglyTypedResourceBuilder
    'с помощью такого средства, как ResGen или Visual Studio.
    'Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    'с параметром /str или перестройте свой проект VS.
    '''<summary>
    '''  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RosterViewer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Перезаписывает свойство CurrentUICulture текущего потока для всех
        '''  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _9999() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_9999", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _99991() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_99991", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_free() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_free", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_raw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_raw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_roh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_roh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_sd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_sd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_tna() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_tna", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_wwe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_wwe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cntoff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cntoff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cnton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cnton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property extreme_rules1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("extreme_rules1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mlogx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mlogx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property push2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("push2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property s1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("s1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SbgTNA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SbgTNA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tna_destination_x_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tna_destination_x_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wm28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wm28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wrestlemania_27_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wrestlemania_27_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property y_b536fffb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("y_b536fffb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
